import reduxService from 'services/redux'

const constants = reduxService.prepareConstants('views/SunriseAuction', [
  'SET_AUCTION_PHASES',
  'SET_PROOF_PROGRESS',
  'SET_HAS_BID_ERROR',
  'SET_BIDDING_IS_COMPLETE',
  'SET_BIDDING_IN_PROGRESS',
  'SET_REVEALING_BUNDLE',
  'SET_HAS_REVEAL_ERROR',
  'ENABLE_ENHANCED_PRIVACY',
  'SET_AUCTION_RESULT',
  'SET_LOADING_WINNING_BIDS',
  'SET_AVAILABLE_WFTM',
  'SET_APPROVED_WFTM',
  'SET_IS_APPROVING_WFTM',
  'SET_IS_CLAIMING_DOMAINS',
  'SET_IS_CLAIMING_DOMAIN',
  'SET_CLAIM_GENERATE_PROOFS',
  'SET_REVEALED_BIDS',
  'SET_LOADED_BID_PROGRESS',
  'WINNING_BIDS_LOADED',
  'SET_GETTING_WFTM',
])

export default constants
